name: Deploy Jupyter Book to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version of Python

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jupyter-book

      - name: Build the book
        run: |
          jupyter-book build .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html

